# Generated by Django 5.2.1 on 2025-06-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ecommerce', '0001_initial'), ('ecommerce', '0002_product_color_product_description_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
